server:
  port: 4006

spring:
  application:
    name: livegoods-gatway
  cloud:
    gateway:
      routes:
        - id: banner
          uri: lb://livegoods-banner
          predicates:
            - Path=/banner
        - id: recommendation
          uri: lb://livegoods-recommendation
          predicates:
            - Path=/recommendation
            - Query=city #请求参数中必须包含city，只能处理get请求
        - id: hotproduct
          uri: lb://livegoods-hot-product
          predicates:
            - Path=/hotProduct
            - Query=city #请求参数中必须包含city，只能处理get请求
        - id: search
          uri: lb://livegoods-search
          predicates:
            - Path=/search
            - Query=city #请求参数中必须包含city，只能处理get请求
            - Query=content
            - Query=page
        - id: search
          uri: lb://livegoods-details
          predicates:
            - Path=/details
            - Query=id
        - id: comments
          uri: lb://livegoods-comments
          predicates:
            - Path=/comment
            - Query=id
            - Query=page
        - id: buytime
          uri: lb://livegoods-buytime
          predicates:
            - Path=/buytime
            - Query=id
        - id: passport
          uri: lb://livegoods-passport
          predicates:
            - Path=/sendyzm,/login
        - id: buyaction
          uri: lb://livegoods-buy-action
          predicates:
            - Path=/buyaction
            - Query=id
            - Query=user
        - id: order
          uri: lb://livegoods-order
          predicates:
            - Path=/order
            - Query=user
        - id: feedback
          uri: lb://livegoods-feedback
          predicates:
            - Path=/feedback



eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
