livegoods:
  nginx:
    server: http://106.55.34.181:8888/
  house:
    redisPrefix: 'livegoods:details::getHouseById'
  amqp:
    buyaction:
      exchange: livegoods-buyaction
      routingKey: buyaction
      queueName: livegoods-buyaction-queue
      exchangeType: topic
    order:
      exchange: livegoods-order
      routingKey: order
      queueName: livegoods-order-queue
      exchangeType: topic
