livegoods:
  nginx:
    server: http://127.0.0.1:8080/
  house:
    redisPrefix: 'livegoods:details::getHouseById'
  amqp:
    buyaction:
      exchange: livegoods-buyaction
      routingKey: buyaction
      queueName: livegoods-buyaction-queue
      exchangeType: topic
    order:
      exchange: livegoods-order
      routingKey: order
      queueName: livegoods-order-queue
      exchangeType: topic
