#server:
#  port: 9010
spring:
  application:
    name: livegoods-consumer-order
  profiles:
    active: commons
  redis:
    host: 106.55.34.181
    port: 6379
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.34.181:3306/lcn?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  rabbitmq:
    host: 106.55.34.181
    port: 5672
    username: livegoods
    password: 123456
    virtual-host: /
tx-lcn:
  client:
    manager-address: 0.0.0.0:8070
    chain-level: 5
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
