server:
  port: 9003
spring:
  application:
    name: livegoods-search
  profiles:
    active: es,commons
  security: #配置静态Security用户名和密码，启动时加载
    user:
      name: livegoods
      password: 123456
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
livegoods:
  search:
    defaultRows: 5
  img:
    middle: 'group1/M00/00/00/'