server:
  port: 9009
spring:
  application:
    name: livegoods-buy-action
  profiles:
    active: commons
  rabbitmq:
    host: 106.55.34.181
    port: 5672
    username: livegoods
    password: chenyide
    virtual-host: /

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://106.55.34.181:8761/eureka/