server:
  port: 9004
spring:
  profiles:
    active: mongo,commons
  application:
    name: livegoods-details
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.55.34.181:3306/lcn?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis: # 提供Redis配置
    host: 106.55.34.181
    port: 6379
    database: 0
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
livegoods:
  details:
    imgMiddle: 'group1/M00/00/00/'
tx-lcn:
  client:
    manager-address: 0.0.0.0:8070