server:
  port: 9006
spring:
  application:
    name: livegoods-buytime
  profiles:
    active: mongo
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/