livegoods:
  banner:
    nginx:
      server: http://127.0.0.1:8080/
spring:
  application:
    name: livegoods-banner
  profiles:
    active: mongo

server:
  port: 9000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/